[window]
width=1700
height=900
title="CrossCosmos"

[grid]
left_margin=15
right_margin=15
top_margin=15
bottom_margin=65
inner_margin=2
#grid_background_color="DARK_GRAY"
#cell_background_color="WHITE"
#blacked_text_color="BLACK"

#[grid.cursor]
#blink_frequency=30
#color1="BLACK"
#color2="DARK_GRAY"

[color]
normal="BLACK"
locked="BLACK"

[advanced]