[window]
width=1400
height=900
title="CrossCosmos"

[grid]
outer_margin=20
inner_margin=2
grid_background_color="DARK_GRAY"
cell_background_color="WHITE"
blacked_text_color="BLACK"

[text]
normal_color="BLACK"
locked_color="BLACK"

[advanced]
text_cursor_blink_frequency=30