[window]
width=1500
height=900
title="CrossCosmos"

[grid]
left_margin=40
right_margin=40
top_margin=15
bottom_margin=65
inner_margin=2
#grid_background_color="DARK_GRAY"
#cell_background_color="WHITE"
#blacked_text_color="BLACK"

[text]
normal_color="BLACK"
locked_color="BLACK"

[advanced]
text_cursor_blink_frequency=30