""" """

PLACEHOLDERS = [r"?", r"-", r" "]

VOWELS = "aeiouAEIOU"
CONSONANTS = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"
ANY_LETTER_RE_PATTERN = "[a-zA-Z]"

NYT_REGULAR_SIZE = 15
NYT_SUNDAY_SIZE = 21
